name: Trigger Cron Job

on:
  schedule:
    - cron: '0 7 * * *'

jobs:
  trigger-cron-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Trigger Cron Job on App
        run: |
          curl -X GET "https://birthday-app-wzww.onrender.com/run-scheduler"
