name: Trigger Cron Job

on:
  schedule:
    - cron: '0 7 * * *'

jobs:
  trigger-cron-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment variables from secrets
        run: |
          echo "SMTP=${{ secrets.SMTP }}" >> $GITHUB_ENV
          echo "SERVER=${{ secrets.SERVER }}" >> $GITHUB_ENV
          echo "GSMTP=${{ secrets.GSMTP }}" >> $GITHUB_ENV  
      
      - name: Trigger Cron Job on App
        run: |
          curl -X GET "https://birthday-app-wzww.onrender.com/run-scheduler"
